WORK = "Work"
SHORT_BREAK = "Short Break"
LONG_BREAK = "Long Break"

DEFAULT_WORK_MINUTES = 25
DEFAULT_SHORT_BREAK_MINUTES = 5
DEFAULT_LONG_BREAK_MINUTES = 15
MIN_INTERVAL_MINUTES = 1
MAX_INTERVAL_MINUTES = 999
WORK_SESSIONS_PER_LONG_BREAK = 4

SECONDS_PER_MINUTE = 60
TICK_INTERVAL_MS = 1000

# Sharper defaults to improve perceptibility on macOS.
WORK_COMPLETE_SOUND = "Ping"
REST_COMPLETE_SOUND = "Sosumi"

SOUND_DIR_ENV = "POMODORO_SOUND_DIR"
SOUND_EXTENSIONS = (".aiff", ".wav", ".mp3", ".m4a")
